const CREATE_PROJECT = 'CREATE_PROJECT'
const GET_TEMPLATES = 'GET_TEMPLATES'
const CHECK_PROJECT_ASSOCIATED = 'CHECK_PROJECT_ASSOCIATED'
const CONNECT_PROJECT = 'CONNECT_PROJECT'
const ToolsList: Record<string, string> = {
    CHECK_PROJECT_ASSOCIATED,
    CREATE_PROJECT,
    CONNECT_PROJECT,
    GET_TEMPLATES
}
export default ToolsList;