apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devzen-wildcard-cert
spec:
  secretName: devzen-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.devzen.ashprojects.tech"
  dnsNames:
    - "*.devzen.ashprojects.tech"
